# -*- coding: utf-8 -*-
"""lesson_71.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vV9rgvPas_TYvLJe3TVOdSkAJ3QeoPOA
"""

import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()
clean_df.tail()

clean_df['Starting Median Salary'].idxmax()

clean_df.loc[43]

clean_df['Mid-Career 10th Percentile Salary'].idxmax()

clean_df.loc[8]

clean_df['Starting Median Salary'].idxmin()

clean_df.loc[49]

clean_df['Mid-Career 10th Percentile Salary'].idxmin()

clean_df.loc[39]

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

highest_potencial = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potencial[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

high_risk = clean_df.sort_values('Spread', ascending=False)
high_risk[['Undergraduate Major', 'Spread']].head()

pd.options.display.float_format = '{:,.2f}'.format 
clean_df.groupby('Group').mean()